### ISSUE TITLE
Reference count is not decreased in certain situations

### ISSUE THREAD

**Issue by nicoweidner** [spdx/Spdx-Java-Library#126]
While writing test cases for a tool, I ran into a confusing scenario. I might be misunderstanding something, so I'll describe the situation as detailed as possible.

- To start with, I have a basic document describing a file (this is used as basis for many test cases). The file is added like this:
```
SpdxFile file = document.createSpdxFile("SPDXRef-somefile", "./foo.txt", concludedLicense, List.of(), "Copyright 2022 some guy", sha1Checksum).build();
document.getDocumentDescribes().add(file);
```
- During debugging, I verified that this `add` call adds a relationship to the document and increases the reference count on the file
- For a specific test case, I wanted to replace the file with a different one, so I tried:
```
document.getDocumentDescribes().remove(file);
IModelStore modelStore = document.getModelStore();
modelStore.delete(documentUri, "SPDXRef-somefile");
```
- However, deletion fails because reference count is still 1

My impression is that `RelatedElementCollection#add` increases the reference count on the file (while creating a relationship, when the file is set as the related element), but `RelatedElementCollection#remove` does not decrease the reference count. As far as I can tell, when the `remove` method is called with the file as parameter, the reference count is decreased on the relationship, but not on the file itself.

So - is there some logic missing, or is this usage not intended? Or am I simply missing some step in the process?

**Comment by goneall** [comment]
@nicoweidner - This looks like a bug.  I'm guessing there is missing logic in the `getDocumentDescribes().remove(file)`.

I'll look into a fix.

I'm 1/2 way through a release of the tools - let me know if it is important to include a fix for this in the next release.

**Comment by goneall** [comment]
@nicoweidner The issue was we were not removing the unused relationship in the relationship collection.

PR #127 should fix this.  Please review.

Note that this can be worked around by deleting the relationship created on the call to `document.getDocumentDescribes().add(file)`.

**Comment by nicoweidner** [comment]
@goneall Thanks! I did a quick local test run with the changes (using the test described above) and it worked.

Side remark: Before using the new changes, I tried removing the relationship before deleting the file, but that did not work. The relationship was gone after this line, but deletion still failed because of reference count being one.
```
document.getRelationships().removeAll(document.getRelationships());
```

And finally: From my side, this is not really important to include in the next release.
